#!/bin/sh

TAG="${1:-latest}"
OPTS="${2:-}"

# build
docker build $OPTS -t npulidom/prerender:$TAG .
echo "\n-> Build success\n"

# image push
if [ "$#" -ne 0 ] && [ "$1" = "push" ]; then
	docker push npulidom/prerender:$TAG
fi
